Nikita nair
broadinstitute/MorphEm pull request #18
Opened 2024-06-20 17:04 UTC by NikitaN18

2024-06-21 15:56 UTC, jccaicedo requested changes
This is looking great! Please address the minor changes in the README file.

2024-06-21 15:56 UTC, jccaicedo commented on README.md
> +## Disclosure
Remove the title

2024-06-21 15:56 UTC, jccaicedo commented on README.md
> +### Notice
Move this title up to include the previous statement.
Change the title from Notice to Note (keep the three hashes)

2024-06-21 15:56 UTC, jccaicedo commented on README.md
> +### Recommended Version:
Remove it

2024-06-21 15:56 UTC, jccaicedo commented on README.md
> +If your python version is not 3.8 or 3.9, install python with
Update to recommend 3.9.

2024-06-21 15:56 UTC, jccaicedo commented on README.md
> +#### Notice
Remove the little titles and only keep the major sections

2024-06-21 18:27 UTC, NikitaN18 commented
Thanks! I made the necessary changes to the README file and made it more organized.

2024-06-25 17:01 UTC, jccaicedo approved these changes
Looks good to me!

2024-06-25 17:01 UTC, merged